### ISSUE TITLE
Переименовать файлы task.md в README.md

### ISSUE THREAD

**Issue by gil9red** [semyon-dev/stepik-go#4]
Тогда, на самих страницах папок task_csv_1 и task_sep_1, имеющих README.md оно будет отображено ниже (как на странице репозитория).
Просто, неудобно заходить в сами файлы task.md, чтобы увидеть суть задачи (хотя это и не требовалось, т.к. хватало на степике) :)

**Comment by semyon-dev** [comment]
Merged in https://github.com/semyon-dev/stepik-go/pull/6
